name: Docker Build CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kodingan dari repository
    - uses: actions/checkout@v4

    # 2. Build Docker Image
    # Karena Dockerfile Anda sudah ada perintah 'mvn package',
    # maka kita cukup jalankan build docker saja.
    - name: Build Docker Image
      run: docker build -t transaksi-app:latest .
